### ISSUE TITLE
rewreite to 15 pages

### ISSUE THREAD

**Issue by timm** [ai-se/why_GALE_-really-_works#13]

**Comment by timm** [comment]
why 15 pages?

have you email ssbse pc chair  to find the target journal? and then we can work our formatting and page length

**Comment by ginfung** [comment]
@timm I contacted the pc chair. He said he would sent us more details later.
![image](https://cloud.githubusercontent.com/assets/3222148/19406958/2348f4ec-9260-11e6-85ce-bac066fc8d15.png)
