### ISSUE TITLE
All the graphs should be in the same place

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/why_GALE_-really-_works#2]

**Comment by ginfung** [comment]
# Old Collection of Results

I create a markdown which contains all tests, to-do list and charts we have done or should do

https://github.com/ai-se/why_GALE_-really-_works/wiki/DataCollection

**Comment by vivekaxl** [comment]
can you put in the link here

**Comment by vivekaxl** [comment]
# Summary:
- IGD values blow GALEX out of the water. There is no point looking at it exception being xomo_flight
- For Hypervolume:
  -- just increasing the sample size to 10X and WHERE does much better than existing GALE
  -- AVG(NSGA2/GALE0) = 1.15 and AVG(SPEA2/GALE0) = 1.156
- For Spread
  -- similar phenomenon as HV  is observed
  -- AVG(NSGA2/ GALE0) = 1.35 and AVG(SPEA2/GALE0) = 1.322

# Hypothesis:
- This is probably because of being in a certain part of frontier. (TODO) Visualization might help
- (TODO) Why can't we use the similar sampling technique to solve this sampling problem. 

# RawData

[Raw_Results.xls.zip](https://github.com/ai-se/why_GALE_-really-_works/files/106811/Raw_Results.xls.zip)

# Graphs:

![figure31_comparisionshypervolume](https://cloud.githubusercontent.com/assets/6147456/12616536/ba591fce-c4d9-11e5-9fec-0d321abae320.png)
![figure32_comparisionsspread](https://cloud.githubusercontent.com/assets/6147456/12616537/ba5b607c-c4d9-11e5-974e-f9188d3a6d22.png)
![figure33_comparisionsigd](https://cloud.githubusercontent.com/assets/6147456/12616535/ba581746-c4d9-11e5-9ec8-058fc7757766.png)

**Comment by vivekaxl** [comment]
# Summary:

- IGD values blow GALEX out of the water. There is no point looking at it exception being xomo_flight

- For Hypervolume:
-- just increasing the sample size to 10X and WHERE does much better than existing GALE
-- AVG(NSGA2/GALE0) = 1.15 and AVG(SPEA2/GALE0) = 1.156

- For Spread
-- similar phenomenon as HV  is observed
-- AVG(NSGA2/ GALE0) = 1.35 and AVG(SPEA2/GALE0) = 1.322

# Hypothesis: 
- This is probably because of being in a certain part of frontier. (TODO) Visualization might help
- (TODO) Why can't we use the similar sampling technique to solve this sampling problem.
